import AppShell from "@/components/AppShell";
import PageHeader from "@/components/PageHeader";
import EmptyState from "@/components/EmptyState";

const SIGNAL_CATEGORIES = [
  {
    id: "OPN",
    label: "Open Source",
    description: "Publicly available information from monitored platforms, publications, and feeds. OSINT signals are classified by source type and recency before entering the intake queue.",
    intakeLogic: "Volume-filtered — relevance scoring applied before logging",
  },
  {
    id: "STR",
    label: "Structured Feeds",
    description: "Machine-readable data streams from defined endpoints — APIs, data exports, and standardized feeds. Structured feeds are ingested on schedule and validated on receipt.",
    intakeLogic: "Schema-validated on intake — malformed records held for review",
  },
  {
    id: "FLG",
    label: "Flagged Patterns",
    description: "Signals generated by pattern detection logic — recurring observations across sources that meet defined threshold criteria for analytical attention.",
    intakeLogic: "Pattern threshold required — single-observation flags are not logged",
  },
  {
    id: "MAN",
    label: "Manual Intake",
    description: "Signals submitted through operator-controlled channels. Manual intake requires classification at submission — unclassified submissions are held in the staging queue.",
    intakeLogic: "Operator-classified before commit — no auto-routing on manual intake",
  },
];

const TRIAGE_RULES = [
  "Source reliability score meets defined intake threshold",
  "Signal type matches a monitored category",
  "Temporal relevance within defined observation window",
  "No duplicate record exists in the index for this signal",
  "Classification can be determined at intake",
];

const FILTERS = ["ALL", "ACTIVE", "STAGED", "DISMISSED"];

export default function SignalsPage() {
  return (
    <AppShell>
      <div className="flex flex-col" style={{ minHeight: "calc(100vh - 84px)" }}>
        <PageHeader
          module="MODULE / SIGNALS"
          title="SIGNALS"
          subtitle="Signal capture, source triage, and intake classification"
          badge="NO FEEDS CONNECTED"
          badgeActive={false}
        >
          {/* Filter strip in header */}
          <div className="flex items-center gap-2">
            {FILTERS.map((f) => (
              <button key={f} data-testid={`filter-${f.toLowerCase()}`}
                className="font-mono-tactical idx-filter-btn rounded px-2.5 py-1"
                style={{
                  border: f === "ALL" ? "1px solid rgba(34,197,94,0.38)" : "1px solid rgba(34,197,94,0.1)",
                  color: f === "ALL" ? "#22c55e" : "rgba(34,197,94,0.35)",
                  background: f === "ALL" ? "rgba(34,197,94,0.06)" : "transparent",
                  fontSize: "9.5px",
                  letterSpacing: "0.1em",
                }}>
                {f}
              </button>
            ))}
          </div>
        </PageHeader>

        <div className="flex flex-1 overflow-hidden">
          {/* Main content */}
          <div className="flex-1 p-6 md:p-7 space-y-5 overflow-y-auto">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {SIGNAL_CATEGORIES.map((cat) => (
                <div key={cat.id} className="rounded p-5 space-y-3 idx-card"
                  style={{ border: "1px solid rgba(34,197,94,0.1)", background: "rgba(0,0,0,0.2)" }}>
                  <div className="flex items-center gap-2.5">
                    <div className="font-mono-tactical px-1.5 py-0.5 rounded flex-shrink-0"
                      style={{
                        border: "1px solid rgba(34,197,94,0.22)",
                        color: "rgba(34,197,94,0.65)",
                        fontSize: "8.5px",
                        letterSpacing: "0.06em",
                        background: "rgba(34,197,94,0.04)",
                      }}>
                      {cat.id}
                    </div>
                    <span className="font-orbitron text-sm font-bold tracking-wider" style={{ color: "#22c55e" }}>
                      {cat.label}
                    </span>
                  </div>
                  <p className="font-mono-tactical leading-relaxed"
                    style={{ color: "rgba(255,255,255,0.38)", lineHeight: "1.88", fontSize: "10.5px" }}>
                    {cat.description}
                  </p>
                  <div className="flex items-center gap-2 pt-1.5" style={{ borderTop: "1px solid rgba(34,197,94,0.07)" }}>
                    <div className="w-1 h-1 rounded-full flex-shrink-0" style={{ background: "rgba(34,197,94,0.28)" }} />
                    <span className="font-mono-tactical italic"
                      style={{ color: "rgba(34,197,94,0.3)", fontSize: "9.5px" }}>
                      {cat.intakeLogic}
                    </span>
                  </div>
                </div>
              ))}
            </div>

            {/* Triage rules */}
            <div className="rounded p-5"
              style={{ border: "1px solid rgba(34,197,94,0.08)", background: "rgba(0,0,0,0.15)" }}>
              <div className="font-mono-tactical tracking-widest uppercase mb-3.5"
                style={{ color: "rgba(34,197,94,0.28)", fontSize: "9.5px", letterSpacing: "0.18em" }}>
                Triage Criteria
              </div>
              <div className="space-y-2">
                {TRIAGE_RULES.map((rule, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <span className="font-mono-tactical flex-shrink-0"
                      style={{ color: "rgba(34,197,94,0.22)", fontSize: "8.5px" }}>
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <div className="w-px h-3 flex-shrink-0" style={{ background: "rgba(34,197,94,0.12)" }} />
                    <span className="font-mono-tactical" style={{ color: "rgba(255,255,255,0.3)", fontSize: "10.5px" }}>
                      {rule}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Empty live feed */}
            <div className="rounded" style={{ border: "1px solid rgba(34,197,94,0.07)", background: "rgba(0,0,0,0.12)" }}>
              <div className="px-4 py-2.5" style={{ borderBottom: "1px solid rgba(34,197,94,0.06)" }}>
                <span className="font-mono-tactical tracking-widest uppercase"
                  style={{ color: "rgba(34,197,94,0.25)", fontSize: "9px", letterSpacing: "0.16em" }}>
                  Live Signal Feed
                </span>
              </div>
              <EmptyState icon="◈" title="No live signals" subtitle="Awaiting source binding — signal log will populate on intake" />
            </div>
          </div>

          {/* Status sidebar */}
          <div className="w-56 xl:w-64 shrink-0 p-5 space-y-5 overflow-y-auto"
            style={{ borderLeft: "1px solid rgba(34,197,94,0.07)" }}>
            <div>
              <div className="font-mono-tactical tracking-widest uppercase mb-3"
                style={{ color: "rgba(34,197,94,0.28)", fontSize: "9px", letterSpacing: "0.16em" }}>
                Intake Status
              </div>
              <div className="space-y-3">
                {[
                  { label: "OPEN SOURCE", value: "Not connected" },
                  { label: "STRUCTURED FEEDS", value: "Not bound" },
                  { label: "PATTERN MONITOR", value: "Inactive" },
                  { label: "MANUAL QUEUE", value: "Empty" },
                  { label: "TRIAGE QUEUE", value: "—" },
                  { label: "LAST SIGNAL", value: "—" },
                ].map((item) => (
                  <div key={item.label} className="flex flex-col gap-0.5">
                    <span className="font-mono-tactical"
                      style={{ fontSize: "8.5px", color: "rgba(34,197,94,0.25)", letterSpacing: "0.1em" }}>
                      {item.label}
                    </span>
                    <span className="font-mono-tactical text-xs" style={{ color: "rgba(34,197,94,0.45)" }}>
                      {item.value}
                    </span>
                  </div>
                ))}
              </div>
            </div>
            <div className="h-px" style={{ background: "rgba(34,197,94,0.06)" }} />
            <p className="font-mono-tactical" style={{ color: "rgba(255,255,255,0.2)", fontSize: "9.5px", lineHeight: "1.8" }}>
              Signal feeds are bound per source category. Each category operates independently.
            </p>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
