import AppShell from "@/components/AppShell";
import EmptyState from "@/components/EmptyState";

const SIGNAL_CATEGORIES = [
  {
    id: "OPN",
    label: "Open Source",
    description: "Publicly available information from monitored platforms, publications, and feeds. OSINT signals are classified by source type and recency before entering the intake queue.",
    intakeLogic: "Volume-filtered — relevance scoring applied before logging",
  },
  {
    id: "STR",
    label: "Structured Feeds",
    description: "Machine-readable data streams from defined endpoints — APIs, data exports, and standardized feeds. Structured feeds are ingested on schedule and validated on receipt.",
    intakeLogic: "Schema-validated on intake — malformed records held for review",
  },
  {
    id: "FLG",
    label: "Flagged Patterns",
    description: "Signals generated by pattern detection logic — recurring observations across sources that meet defined threshold criteria for analytical attention.",
    intakeLogic: "Pattern threshold required — single-observation flags are not logged",
  },
  {
    id: "MAN",
    label: "Manual Intake",
    description: "Signals submitted through operator-controlled intake channels. Manual intake requires classification at submission — unclassified submissions are held in the staging queue.",
    intakeLogic: "Operator-classified before commit — no auto-routing on manual intake",
  },
];

const TRIAGE_CRITERIA = [
  "Source reliability score meets intake threshold",
  "Signal type matches a defined category",
  "Temporal relevance within defined observation window",
  "No duplicate record exists in the index for this signal",
  "Classification can be determined at intake",
];

const FILTERS = ["ALL", "ACTIVE", "STAGED", "DISMISSED"];

export default function SignalsPage() {
  return (
    <AppShell>
      <div className="flex flex-col h-full" style={{ minHeight: "calc(100vh - 84px)" }}>
        <div className="px-6 md:px-8 py-4 shrink-0" style={{ borderBottom: "1px solid rgba(34,197,94,0.08)" }}>
          <div className="flex items-start justify-between gap-4 flex-wrap">
            <div>
              <div className="font-mono-tactical text-xs tracking-widest uppercase mb-2" style={{ color: "rgba(34,197,94,0.4)" }}>
                MODULE / SIGNALS
              </div>
              <h1 className="font-orbitron text-3xl font-bold tracking-wider" style={{ color: "#22c55e", textShadow: "0 0 20px rgba(34,197,94,0.2)" }}>
                SIGNALS
              </h1>
              <p className="mt-2 font-mono-tactical text-xs" style={{ color: "rgba(255,255,255,0.35)", lineHeight: "1.9" }}>
                Signal capture, source triage, and intake classification workspace
              </p>
            </div>
            <div className="flex items-center gap-2 px-3 py-1.5 rounded font-mono-tactical text-xs tracking-widest"
              style={{ border: "1px solid rgba(34,197,94,0.15)", color: "rgba(34,197,94,0.45)", background: "rgba(34,197,94,0.03)" }}>
              <div className="w-1.5 h-1.5 rounded-full" style={{ background: "rgba(34,197,94,0.35)" }} />
              NO FEEDS CONNECTED
            </div>
          </div>

          <div className="flex items-center gap-3 mt-4">
            {FILTERS.map((f) => (
              <button key={f} data-testid={`filter-${f.toLowerCase()}`}
                className="font-mono-tactical text-xs px-3 py-1 rounded"
                style={{
                  border: f === "ALL" ? "1px solid rgba(34,197,94,0.38)" : "1px solid rgba(34,197,94,0.1)",
                  color: f === "ALL" ? "#22c55e" : "rgba(34,197,94,0.38)",
                  background: f === "ALL" ? "rgba(34,197,94,0.07)" : "transparent",
                  letterSpacing: "0.12em",
                }}>
                {f}
              </button>
            ))}
            <div className="flex-1" />
            <div className="flex items-center gap-2 px-3 py-1.5 rounded"
              style={{ border: "1px solid rgba(34,197,94,0.1)", background: "rgba(0,0,0,0.3)" }}>
              <span className="font-mono-tactical text-xs" style={{ color: "rgba(34,197,94,0.25)", fontSize: "10px" }}>SEARCH</span>
              <div className="w-px h-3" style={{ background: "rgba(34,197,94,0.15)" }} />
              <span className="font-mono-tactical text-xs w-36" style={{ color: "rgba(34,197,94,0.18)" }}>Filter signals...</span>
            </div>
          </div>
        </div>

        <div className="flex flex-1 overflow-hidden">
          <div className="flex-1 flex flex-col overflow-y-auto p-5 gap-5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {SIGNAL_CATEGORIES.map((cat) => (
                <div key={cat.id} className="rounded p-4 space-y-2.5"
                  style={{ border: "1px solid rgba(34,197,94,0.1)", background: "rgba(0,0,0,0.2)" }}>
                  <div className="flex items-center gap-2.5">
                    <div className="font-mono-tactical text-xs px-1.5 py-0.5 rounded"
                      style={{ border: "1px solid rgba(34,197,94,0.2)", color: "rgba(34,197,94,0.6)", fontSize: "9px" }}>
                      {cat.id}
                    </div>
                    <span className="font-orbitron text-xs font-bold tracking-wider" style={{ color: "#22c55e" }}>
                      {cat.label}
                    </span>
                  </div>
                  <p className="font-mono-tactical text-xs leading-relaxed" style={{ color: "rgba(255,255,255,0.38)", lineHeight: "1.85", fontSize: "10.5px" }}>
                    {cat.description}
                  </p>
                  <div className="pt-1.5" style={{ borderTop: "1px solid rgba(34,197,94,0.07)" }}>
                    <span className="font-mono-tactical text-xs italic" style={{ color: "rgba(34,197,94,0.32)", fontSize: "9.5px" }}>
                      {cat.intakeLogic}
                    </span>
                  </div>
                </div>
              ))}
            </div>

            <div className="rounded p-4" style={{ border: "1px solid rgba(34,197,94,0.08)", background: "rgba(0,0,0,0.15)" }}>
              <div className="font-mono-tactical text-xs tracking-widest uppercase mb-3" style={{ color: "rgba(34,197,94,0.3)", fontSize: "9px" }}>
                Triage Criteria
              </div>
              <div className="space-y-2">
                {TRIAGE_CRITERIA.map((c, i) => (
                  <div key={i} className="flex items-center gap-2.5">
                    <div className="w-1 h-1 rounded-full flex-shrink-0" style={{ background: "rgba(34,197,94,0.35)" }} />
                    <span className="font-mono-tactical text-xs" style={{ color: "rgba(255,255,255,0.3)", fontSize: "10.5px" }}>{c}</span>
                  </div>
                ))}
              </div>
            </div>

            <EmptyState icon="◈" title="No live signals" subtitle="Source binding pending — signal log will populate here on intake" />
          </div>

          <div className="w-60 xl:w-72 shrink-0 p-4 space-y-4 overflow-y-auto" style={{ borderLeft: "1px solid rgba(34,197,94,0.07)" }}>
            <div className="font-mono-tactical text-xs tracking-widest uppercase" style={{ color: "rgba(34,197,94,0.28)", fontSize: "9px" }}>
              Intake Status
            </div>
            <div className="space-y-2.5">
              {[
                { label: "PRIMARY SOURCE", value: "Not connected" },
                { label: "STRUCTURED FEEDS", value: "Not bound" },
                { label: "PATTERN MONITOR", value: "Inactive" },
                { label: "MANUAL QUEUE", value: "Empty" },
                { label: "TRIAGE QUEUE", value: "—" },
                { label: "LAST SIGNAL", value: "—" },
              ].map((item) => (
                <div key={item.label} className="flex flex-col gap-0.5">
                  <span className="font-mono-tactical" style={{ fontSize: "9px", color: "rgba(34,197,94,0.28)", letterSpacing: "0.08em" }}>
                    {item.label}
                  </span>
                  <span className="font-mono-tactical text-xs" style={{ color: "rgba(34,197,94,0.45)" }}>
                    {item.value}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
